// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzfxbfdkutpvyinhzobf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZnhiZmRrdXRwdnlpbmh6b2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMDgwNzAsImV4cCI6MjA1MjY4NDA3MH0.lHRZAboOSEaTCO3PxPh1W94JR7gj2yWNl7IRmPeOmq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);